export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin"
export PATH="/Library/TeX/texbin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export RUST_SRC_PATH="$HOME/dotfiles/rust/src"
export ECLIPSE_HOME="/Applications/Eclipse.app/Contents/Eclipse"
